-- ROOMS
INSERT INTO rooms (room_number, floor, capacity, occupied, type, status, has_ac, has_wifi, has_attached_bathroom, monthly_rent, created_at, updated_at) VALUES ('G-101', 0, 6, 0, 'DORMITORY', 'AVAILABLE', false, true, false, 3000.00, NOW(), NOW());
INSERT INTO rooms (room_number, floor, capacity, occupied, type, status, has_ac, has_wifi, has_attached_bathroom, monthly_rent, created_at, updated_at) VALUES ('G-102', 0, 6, 0, 'DORMITORY', 'AVAILABLE', false, true, false, 3000.00, NOW(), NOW());
INSERT INTO rooms (room_number, floor, capacity, occupied, type, status, has_ac, has_wifi, has_attached_bathroom, monthly_rent, created_at, updated_at) VALUES ('G-103', 0, 4, 0, 'STANDARD', 'AVAILABLE', false, true, false, 4000.00, NOW(), NOW());
INSERT INTO rooms (room_number, floor, capacity, occupied, type, status, has_ac, has_wifi, has_attached_bathroom, monthly_rent, created_at, updated_at) VALUES ('G-104', 0, 4, 0, 'STANDARD', 'AVAILABLE', false, true, false, 4000.00, NOW(), NOW());
INSERT INTO rooms (room_number, floor, capacity, occupied, type, status, has_ac, has_wifi, has_attached_bathroom, monthly_rent, created_at, updated_at) VALUES ('G-105', 0, 3, 0, 'STANDARD', 'AVAILABLE', true, true, false, 5000.00, NOW(), NOW());
INSERT INTO rooms (room_number, floor, capacity, occupied, type, status, has_ac, has_wifi, has_attached_bathroom, monthly_rent, created_at, updated_at) VALUES ('G-106', 0, 3, 0, 'STANDARD', 'MAINTENANCE', true, true, true, 5500.00, NOW(), NOW());
INSERT INTO rooms (room_number, floor, capacity, occupied, type, status, has_ac, has_wifi, has_attached_bathroom, monthly_rent, created_at, updated_at) VALUES ('1-201', 1, 3, 0, 'STANDARD', 'AVAILABLE', true, true, false, 5000.00, NOW(), NOW());
INSERT INTO rooms (room_number, floor, capacity, occupied, type, status, has_ac, has_wifi, has_attached_bathroom, monthly_rent, created_at, updated_at) VALUES ('1-202', 1, 3, 0, 'STANDARD', 'AVAILABLE', true, true, false, 5000.00, NOW(), NOW());
INSERT INTO rooms (room_number, floor, capacity, occupied, type, status, has_ac, has_wifi, has_attached_bathroom, monthly_rent, created_at, updated_at) VALUES ('1-203', 1, 2, 0, 'DELUXE', 'AVAILABLE', true, true, true, 7000.00, NOW(), NOW());
INSERT INTO rooms (room_number, floor, capacity, occupied, type, status, has_ac, has_wifi, has_attached_bathroom, monthly_rent, created_at, updated_at) VALUES ('1-204', 1, 2, 0, 'DELUXE', 'AVAILABLE', true, true, true, 7000.00, NOW(), NOW());
INSERT INTO rooms (room_number, floor, capacity, occupied, type, status, has_ac, has_wifi, has_attached_bathroom, monthly_rent, created_at, updated_at) VALUES ('1-205', 1, 2, 0, 'DELUXE', 'AVAILABLE', true, true, true, 7000.00, NOW(), NOW());
INSERT INTO rooms (room_number, floor, capacity, occupied, type, status, has_ac, has_wifi, has_attached_bathroom, monthly_rent, created_at, updated_at) VALUES ('1-206', 1, 2, 0, 'DELUXE', 'AVAILABLE', true, true, true, 7500.00, NOW(), NOW());
INSERT INTO rooms (room_number, floor, capacity, occupied, type, status, has_ac, has_wifi, has_attached_bathroom, monthly_rent, created_at, updated_at) VALUES ('2-301', 2, 2, 0, 'DELUXE', 'AVAILABLE', true, true, true, 7500.00, NOW(), NOW());
INSERT INTO rooms (room_number, floor, capacity, occupied, type, status, has_ac, has_wifi, has_attached_bathroom, monthly_rent, created_at, updated_at) VALUES ('2-302', 2, 2, 0, 'DELUXE', 'AVAILABLE', true, true, true, 7500.00, NOW(), NOW());
INSERT INTO rooms (room_number, floor, capacity, occupied, type, status, has_ac, has_wifi, has_attached_bathroom, monthly_rent, created_at, updated_at) VALUES ('2-303', 2, 1, 0, 'SUITE', 'AVAILABLE', true, true, true, 12000.00, NOW(), NOW());
INSERT INTO rooms (room_number, floor, capacity, occupied, type, status, has_ac, has_wifi, has_attached_bathroom, monthly_rent, created_at, updated_at) VALUES ('2-304', 2, 1, 0, 'SUITE', 'AVAILABLE', true, true, true, 12000.00, NOW(), NOW());
INSERT INTO rooms (room_number, floor, capacity, occupied, type, status, has_ac, has_wifi, has_attached_bathroom, monthly_rent, created_at, updated_at) VALUES ('2-305', 2, 1, 0, 'SUITE', 'RESERVED', true, true, true, 12000.00, NOW(), NOW());
INSERT INTO rooms (room_number, floor, capacity, occupied, type, status, has_ac, has_wifi, has_attached_bathroom, monthly_rent, created_at, updated_at) VALUES ('2-306', 2, 1, 0, 'SUITE', 'AVAILABLE', true, true, true, 15000.00, NOW(), NOW());

-- STUDENTS
INSERT INTO students (name, email, phone, enrollment_number, department, study_year, gender, guardian_name, guardian_phone, address, date_of_birth, room_id, status, mess_opt_in, created_at, updated_at) VALUES ('Aarav Sharma', 'aarav.sharma@university.edu', '9876543210', 'CSE2023001', 'Computer Science', 2, 'Male', 'Rajesh Sharma', '9876543200', '45 MG Road, Bhopal, MP', '2004-03-15', 1, 'ACTIVE', true, NOW(), NOW());
INSERT INTO students (name, email, phone, enrollment_number, department, study_year, gender, guardian_name, guardian_phone, address, date_of_birth, room_id, status, mess_opt_in, created_at, updated_at) VALUES ('Priya Patel', 'priya.patel@university.edu', '9876543211', 'ECE2023002', 'Electronics', 2, 'Female', 'Suresh Patel', '9876543201', '12 Lake View, Indore, MP', '2004-07-22', 1, 'ACTIVE', true, NOW(), NOW());
INSERT INTO students (name, email, phone, enrollment_number, department, study_year, gender, guardian_name, guardian_phone, address, date_of_birth, room_id, status, mess_opt_in, created_at, updated_at) VALUES ('Rohit Verma', 'rohit.verma@university.edu', '9876543212', 'ME2022003', 'Mechanical', 3, 'Male', 'Amit Verma', '9876543202', '78 Station Road, Jabalpur, MP', '2003-11-08', 3, 'ACTIVE', true, NOW(), NOW());
INSERT INTO students (name, email, phone, enrollment_number, department, study_year, gender, guardian_name, guardian_phone, address, date_of_birth, room_id, status, mess_opt_in, created_at, updated_at) VALUES ('Sneha Gupta', 'sneha.gupta@university.edu', '9876543213', 'CSE2023004', 'Computer Science', 2, 'Female', 'Vikram Gupta', '9876543203', '23 Civil Lines, Gwalior, MP', '2004-01-30', 7, 'ACTIVE', false, NOW(), NOW());
INSERT INTO students (name, email, phone, enrollment_number, department, study_year, gender, guardian_name, guardian_phone, address, date_of_birth, room_id, status, mess_opt_in, created_at, updated_at) VALUES ('Arjun Singh', 'arjun.singh@university.edu', '9876543214', 'CE2021005', 'Civil', 4, 'Male', 'Pratap Singh', '9876543204', '56 Nehru Nagar, Ujjain, MP', '2002-09-14', 9, 'ACTIVE', true, NOW(), NOW());
INSERT INTO students (name, email, phone, enrollment_number, department, study_year, gender, guardian_name, guardian_phone, address, date_of_birth, room_id, status, mess_opt_in, created_at, updated_at) VALUES ('Kavya Joshi', 'kavya.joshi@university.edu', '9876543215', 'IT2023006', 'Information Technology', 2, 'Female', 'Ramesh Joshi', '9876543205', '89 Saket Nagar, Bhopal, MP', '2004-05-19', 9, 'ACTIVE', true, NOW(), NOW());
INSERT INTO students (name, email, phone, enrollment_number, department, study_year, gender, guardian_name, guardian_phone, address, date_of_birth, room_id, status, mess_opt_in, created_at, updated_at) VALUES ('Vikash Kumar', 'vikash.kumar@university.edu', '9876543216', 'CSE2024007', 'Computer Science', 1, 'Male', 'Sunil Kumar', '9876543206', '34 Arera Colony, Bhopal, MP', '2005-12-03', NULL, 'ACTIVE', true, NOW(), NOW());
INSERT INTO students (name, email, phone, enrollment_number, department, study_year, gender, guardian_name, guardian_phone, address, date_of_birth, room_id, status, mess_opt_in, created_at, updated_at) VALUES ('Ananya Mishra', 'ananya.mishra@university.edu', '9876543217', 'ECE2024008', 'Electronics', 1, 'Female', 'Deepak Mishra', '9876543207', '67 Kolar Road, Bhopal, MP', '2005-08-25', NULL, 'ACTIVE', true, NOW(), NOW());
INSERT INTO students (name, email, phone, enrollment_number, department, study_year, gender, guardian_name, guardian_phone, address, date_of_birth, room_id, status, mess_opt_in, created_at, updated_at) VALUES ('Rahul Yadav', 'rahul.yadav@university.edu', '9876543218', 'ME2020009', 'Mechanical', 4, 'Male', 'Mohan Yadav', '9876543208', '90 Hoshangabad Road, Bhopal, MP', '2001-04-11', 15, 'ACTIVE', false, NOW(), NOW());
INSERT INTO students (name, email, phone, enrollment_number, department, study_year, gender, guardian_name, guardian_phone, address, date_of_birth, room_id, status, mess_opt_in, created_at, updated_at) VALUES ('Diya Agarwal', 'diya.agarwal@university.edu', '9876543219', 'CSE2022010', 'Computer Science', 3, 'Female', 'Naresh Agarwal', '9876543209', '11 New Market, Bhopal, MP', '2003-06-07', 13, 'ACTIVE', true, NOW(), NOW());

-- Update room occupancy
UPDATE rooms SET occupied = 2 WHERE room_number = 'G-101';
UPDATE rooms SET occupied = 1 WHERE room_number = 'G-103';
UPDATE rooms SET occupied = 1 WHERE room_number = '1-201';
UPDATE rooms SET occupied = 2 WHERE room_number = '1-203';
UPDATE rooms SET occupied = 1 WHERE room_number = '2-303';
UPDATE rooms SET occupied = 1 WHERE room_number = '2-301';

-- FEES
INSERT INTO fees (student_id, total_amount, paid_amount, payment_status, fee_type, semester, due_date, payment_date, transaction_id, payment_method, remarks, created_at, updated_at) VALUES (1, 15000.00, 15000.00, 'PAID', 'HOSTEL_RENT', '2025-I', '2025-01-31', '2025-01-20', 'TXN-001', 'UPI', 'Paid on time', NOW(), NOW());
INSERT INTO fees (student_id, total_amount, paid_amount, payment_status, fee_type, semester, due_date, payment_date, transaction_id, payment_method, remarks, created_at, updated_at) VALUES (2, 15000.00, 8000.00, 'PARTIAL', 'HOSTEL_RENT', '2025-I', '2025-01-31', NULL, 'TXN-002', 'BANK_TRANSFER', 'Partial payment', NOW(), NOW());
INSERT INTO fees (student_id, total_amount, paid_amount, payment_status, fee_type, semester, due_date, payment_date, transaction_id, payment_method, remarks, created_at, updated_at) VALUES (3, 20000.00, 0.00, 'OVERDUE', 'HOSTEL_RENT', '2025-I', '2025-01-31', NULL, NULL, NULL, 'No payment', NOW(), NOW());
INSERT INTO fees (student_id, total_amount, paid_amount, payment_status, fee_type, semester, due_date, payment_date, transaction_id, payment_method, remarks, created_at, updated_at) VALUES (4, 15000.00, 15000.00, 'PAID', 'HOSTEL_RENT', '2025-I', '2025-01-31', '2025-01-15', 'TXN-004', 'ONLINE', 'Early payment', NOW(), NOW());
INSERT INTO fees (student_id, total_amount, paid_amount, payment_status, fee_type, semester, due_date, payment_date, transaction_id, payment_method, remarks, created_at, updated_at) VALUES (5, 35000.00, 0.00, 'PENDING', 'HOSTEL_RENT', '2025-I', '2026-06-30', NULL, NULL, NULL, NULL, NOW(), NOW());
INSERT INTO fees (student_id, total_amount, paid_amount, payment_status, fee_type, semester, due_date, payment_date, transaction_id, payment_method, remarks, created_at, updated_at) VALUES (1, 5000.00, 5000.00, 'PAID', 'MESS_FEE', '2025-I', '2025-02-15', '2025-02-10', 'TXN-006', 'UPI', NULL, NOW(), NOW());
INSERT INTO fees (student_id, total_amount, paid_amount, payment_status, fee_type, semester, due_date, payment_date, transaction_id, payment_method, remarks, created_at, updated_at) VALUES (6, 5000.00, 0.00, 'PENDING', 'MESS_FEE', '2025-I', '2026-06-30', NULL, NULL, NULL, NULL, NOW(), NOW());
INSERT INTO fees (student_id, total_amount, paid_amount, payment_status, fee_type, semester, due_date, payment_date, transaction_id, payment_method, remarks, created_at, updated_at) VALUES (3, 10000.00, 10000.00, 'PAID', 'SECURITY_DEPOSIT', '2025-I', '2025-01-15', '2025-01-10', 'TXN-008', 'CHEQUE', 'Refundable', NOW(), NOW());

-- COMPLAINTS
INSERT INTO complaints (student_id, title, description, category, priority, status, resolution, assigned_to, resolved_at, created_at, updated_at) VALUES (1, 'Water leakage in bathroom', 'Continuous water leakage from bathroom ceiling pipe causing safety hazard.', 'PLUMBING', 'HIGH', 'RESOLVED', 'Pipe replaced by maintenance.', 'Mr. Rajendra', '2025-02-15 14:30:00', '2025-02-10 09:00:00', '2025-02-15 14:30:00');
INSERT INTO complaints (student_id, title, description, category, priority, status, resolution, assigned_to, resolved_at, created_at, updated_at) VALUES (3, 'WiFi issues on Ground Floor', 'WiFi signal extremely weak in rooms G-103 and G-104. Cannot attend online classes.', 'INTERNET', 'HIGH', 'IN_PROGRESS', NULL, 'IT Support Team', NULL, '2025-03-01 11:00:00', '2025-03-02 10:00:00');
INSERT INTO complaints (student_id, title, description, category, priority, status, resolution, assigned_to, resolved_at, created_at, updated_at) VALUES (5, 'Mess food quality dropped', 'Dinner meals quality has dropped significantly. Rice undercooked and vegetables bland.', 'FOOD', 'MEDIUM', 'OPEN', NULL, NULL, NULL, '2025-03-10 19:30:00', '2025-03-10 19:30:00');
INSERT INTO complaints (student_id, title, description, category, priority, status, resolution, assigned_to, resolved_at, created_at, updated_at) VALUES (2, 'Broken window latch', 'Window latch broken and cannot be properly closed. Security concern at night.', 'MAINTENANCE', 'MEDIUM', 'RESOLVED', 'Window latch replaced.', 'Mr. Suresh', '2025-02-28 16:00:00', '2025-02-25 08:30:00', '2025-02-28 16:00:00');
INSERT INTO complaints (student_id, title, description, category, priority, status, resolution, assigned_to, resolved_at, created_at, updated_at) VALUES (6, 'Noisy construction nearby', 'Construction work continues past 10 PM causing disturbance during study hours.', 'NOISE', 'LOW', 'REJECTED', 'REJECTED: City-authorized work ending April 15. Earplugs distributed.', 'Warden Office', '2025-03-05 10:00:00', '2025-03-03 22:00:00', '2025-03-05 10:00:00');
INSERT INTO complaints (student_id, title, description, category, priority, status, resolution, assigned_to, resolved_at, created_at, updated_at) VALUES (9, 'Power outage in Suite 2-303', 'Complete power failure since yesterday evening. Emergency light also not working.', 'ELECTRICAL', 'CRITICAL', 'ESCALATED', NULL, 'Chief Electrician', NULL, '2025-03-15 18:00:00', '2025-03-16 09:00:00');